// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHadiXU6NnFReVgCBEIMynZK4lJnvwkk',
    appId: '1:28445900517:web:d57cfdedf1da8d046c9e0c',
    messagingSenderId: '28445900517',
    projectId: 'foodpoint-71b1d',
    authDomain: 'foodpoint-71b1d.firebaseapp.com',
    storageBucket: 'foodpoint-71b1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3j8ycYuqyeMcLcr_JZLXtnOi5oMrqtY',
    appId: '1:28445900517:android:a5a224ff865c99586c9e0c',
    messagingSenderId: '28445900517',
    projectId: 'foodpoint-71b1d',
    storageBucket: 'foodpoint-71b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3pAebpYh9z7UFiq0DN6RE9iDmpU7Ychc',
    appId: '1:28445900517:ios:46ffd20253bd5dcb6c9e0c',
    messagingSenderId: '28445900517',
    projectId: 'foodpoint-71b1d',
    storageBucket: 'foodpoint-71b1d.firebasestorage.app',
    iosBundleId: 'com.example.foodPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3pAebpYh9z7UFiq0DN6RE9iDmpU7Ychc',
    appId: '1:28445900517:ios:46ffd20253bd5dcb6c9e0c',
    messagingSenderId: '28445900517',
    projectId: 'foodpoint-71b1d',
    storageBucket: 'foodpoint-71b1d.firebasestorage.app',
    iosBundleId: 'com.example.foodPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXHadiXU6NnFReVgCBEIMynZK4lJnvwkk',
    appId: '1:28445900517:web:3a0f8cbccfbb58ef6c9e0c',
    messagingSenderId: '28445900517',
    projectId: 'foodpoint-71b1d',
    authDomain: 'foodpoint-71b1d.firebaseapp.com',
    storageBucket: 'foodpoint-71b1d.firebasestorage.app',
  );
}
